name: ğŸ›¢ Staging Back

on:
  push:
    branches:
    - staging

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read
  checks: write

defaults:
  run: 
    working-directory: backend

jobs:
  gobuild:
    name: â¬£ Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/go-build
        with:
          go-version: '1.22.1'
          build-path: './cmd/event-reservation-app/*.go'
          output-name: 'leviosa'
  gotest:
    name: ğŸ§ª Golang tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/go-test
        with:
          go-version: '1.22.1'
          test-path: './...'
  docker-back:
    name: ğŸ³ Build backend application docker image
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v3
      - uses: ./.github/actions/push-docker-image
        with:
          tag: 'staging-backend'
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }} 
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          folder: backend
          file: Dockerfile.staging
